version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresql-jsonb-demo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jsonb_demo_2024
      POSTGRES_DB: postgresql_jsonb_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-jsonb-demo
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jsonbdemo.com
      PGADMIN_DEFAULT_PASSWORD: Azure@123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: